// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLIu58kG2hvGtZWQyWGSpXvaRzOmO3fGU',
    appId: '1:170317818551:web:21018f7bbd6d43710fbb32',
    messagingSenderId: '170317818551',
    projectId: 'mulinda-5717f',
    authDomain: 'mulinda-5717f.firebaseapp.com',
    storageBucket: 'mulinda-5717f.firebasestorage.app',
    measurementId: 'G-9KWVWR47DN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChvJ3PL8P8oJuF0faIMteFKl9UR15T0AE',
    appId: '1:170317818551:android:0c89a104f4d07e2b0fbb32',
    messagingSenderId: '170317818551',
    projectId: 'mulinda-5717f',
    storageBucket: 'mulinda-5717f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLIu58kG2hvGtZWQyWGSpXvaRzOmO3fGU',
    appId: '1:170317818551:web:64dc4043a16f1dc60fbb32',
    messagingSenderId: '170317818551',
    projectId: 'mulinda-5717f',
    authDomain: 'mulinda-5717f.firebaseapp.com',
    storageBucket: 'mulinda-5717f.firebasestorage.app',
    measurementId: 'G-N28B29197H',
  );
}
